---
- name: Add the user
  ansible.builtin.user:
    name: "{{ linux_user }}"
    password: "{{ linux_pw | password_hash('sha512') }}"
    shell: /bin/bash
    comment: Student
    update_password: on_create