---
- name: Add the splunk user
  ansible.builtin.user:
    name: "{{ splunk_nix_user }}"
    home: "{{ splunk_home }}"
    password: "{{ splunk_user_pw | password_hash('sha512') }}"
    shell: /bin/bash
    uid: 10777
    comment: Splunk User
    update_password: on_create