- name: Enable splunk boot-start via systemd
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ splunk_nix_user }} -systemd-managed 1 --answer-yes --auto-ports --no-prompt --accept-license"
  become: true
  notify:
    - reload systemctl daemon